### ISSUE TITLE
Airship Pirates 1.14.4 Critical Path

### ISSUE THREAD

**Issue by TylerS1066** [TylerS1066/Movecraft-Plugins#1]
- [x] Stabilize on 1.12.2
   - [x] Finalize Deadbolt-Reloaded
   - [x] Convert servers from some older outdated plugins to newer ones
- [x] Stabilize plugins for 1.14.4 (below are some help wanted issues for each plugin, there are many more before each plugin is 1.14.4 stable)
   - [x] iFill (https://github.com/APDevTeam/iFill/issues/2 & https://github.com/APDevTeam/iFill/issues/3)
   - [x] Cargo (https://github.com/APDevTeam/APCargoMerchant/issues/4 & https://github.com/APDevTeam/APCargoMerchant/issues/5)
   - [x] StructureBoxes (https://github.com/APDevTeam/StructureBoxes/issues/1)
   - [x] AP-Turrets (~~https://github.com/APDevTeam/Ap-Turrets/issues/11~~)
   - [x] Combat (https://github.com/TylerS1066/Movecraft-Combat/issues/74)
   - [x] Cannons (https://github.com/TylerS1066/Movecraft-Cannons/issues/1)
   - [x] Find replacement for AreaShop: https://github.com/md5sha256/AreaShop/releases
- [x] Update Build to 1.14.4
   - [x] Update craft types
   - [x] All the other update things
 - [x] Stabilize on 1.14.4
   - [x] Find replacement for CreeperHeal
 - [x] Update Survival to 1.14.4

**Comment by drfiveminusmint** [comment]
https://github.com/NLthijs48/AreaShop

This might work as an AreaShop replacement, it's licensed under GPL so no issues there

**Comment by TylerS1066** [comment]
> https://github.com/NLthijs48/AreaShop
> 
> This might work as an AreaShop replacement, it's licensed under GPL so no issues there

It might, but it's not been seriously updated in two years.

I'd like to try using [AdvancedRegionMarket](https://www.spigotmc.org/resources/advancedregionmarket.58732/) and [ARM Importer](https://www.spigotmc.org/resources/arm-importer.67515/).

**Comment by TylerS1066** [comment]
~~https://github.com/TylerS1066/Airship-Pirates-Crafts/issues/3
iFill problems~~

**Comment by TylerS1066** [comment]
~~[add publish feature to WarfareBot](https://github.com/TylerS1066/WarfareBot/issues/1)~~

**Comment by TylerS1066** [comment]
~~combat not showing glowstone tracers when I'm not around~~ seems to only be one player, might be a client mod

**Comment by TylerS1066** [comment]
- [x] https://github.com/APDevTeam/Airship-Pirates-Crafts/issues/6
- [x] ~~https://github.com/APDevTeam/Movecraft-Repair/issues/15~~ https://github.com/APDevTeam/Repair-Upgrader/issues/1
